version: "3.9"

services:
  backend:
    build: .
    container_name: portfolio-backend
    ports:
      - "3001:3001"
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - /app/node_modules
    env_file:
      - .env
    restart: unless-stopped